console.log("nyaaa1");
console.log("nyaaa3");
const nyaooo = "nya";
console.log("nyaaa3");
console.log("nya3");
console.log("nyaa3");
console.log("ny3");
const a = "nya";
const b = "nyaa";
const c = "nyaaa";
const d = "nyaaaa";
const nya = "nyaaa";
