name: Auto Update Dev Branch

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]
    types: [closed]

jobs:
  auto-update:
    if: github.event_name == 'push' || (github.event.pull_request.merged == true)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: dev
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Add line to file
        run: |
          echo 'const a = "nya"' >> index.js

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Auto update: add nya line" || exit 0
          git push
